Give a default function to releaseClient callback
graphile/worker pull request #242
Opened 2021-12-07 23:15 UTC by countcain

## Description

First of all, thank you for your library. I discovered a bug today.

![Screen Shot 2021-12-07 at 6 05 04 PM](https://user-images.githubusercontent.com/1751150/145120052-0a12c9c1-5272-4610-b3d0-e189c2e7130d.png)

The callback passed to `pool.connect(callback)` [in this case](https://github.com/brianc/node-postgres/blob/master/packages/pg-pool/index.js#L166) will only be called with an error. Therefore, `releaseClient` can be undefined.

## Performance impact

n/a

## Security impact

n/a

## Checklist

- [x] My code matches the project's code style and `yarn lint:fix` passes.
- [ ] I've added tests for the new feature, and `yarn test` passes.
- [ ] I have detailed the new feature in the relevant documentation.
- [ ] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
- [ ] If this is a breaking change I've explained why.

2021-12-08 15:53 UTC, benjie requested changes
Good catch; please remove the default parameter and instead change line 204 to `releaseClient?.();` - the issue here is that the `!active` handling is triggered before the `err` is handled. (Technically the types are wrong and we should define it as an overloaded function, but that seems a lot of effort.)

2021-12-08 16:42 UTC, countcain commented
@benjie I see. I've updated L204.

2021-12-08 23:42 UTC, benjie approved these changes
Great spot 👍

2021-12-09 00:00 UTC, countcain commented
thank you! It would be very nice if you can merge this and release a patch version.

2021-12-16 15:18 UTC, merged

2021-12-16 15:21 UTC, benjie commented
Oh gosh sorry, this completely got buried :grimacing: Thanks for the fix - it's out now in 0.12.2.