#285 crontab job keys
graphile/worker pull request #294
Opened 2022-10-19 20:50 UTC by spiffytech

## Description

Implements #285: if a cron job would reschedule (due to an error or just not getting picked up), only ever schedule one copy of the job if the crontab includes a `jobKey` parameter.scord discussion/etc as appropriate -->

## Performance impact

Unknown

## Security impact

Unknown

## Checklist

- [ ] My code matches the project's code style and `yarn lint:fix` passes.
- [ ] I've added tests for the new feature, and `yarn test` passes.
- [X] I have detailed the new feature in the relevant documentation.
- [X] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
`yarn lint:fix` fails with this:
```
$ yarn lint fix
yarn run v1.22.19
$ yarn prettier:check && eslint --ext .js,.jsx,.ts,.tsx,.graphql . fix
$ prettier --ignore-path .eslintignore --check '**/*.{js,jsx,ts,tsx,graphql,md,json}'
Checking formatting...
All matched files use Prettier code style!

Oops! Something went wrong! :(

ESLint: 8.18.0

No files matching the pattern "fix" were found.
Please check for typing mistakes in the pattern.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

`yarn test` from inside the container fails with this:

```
$ docker compose exec app yarn test   
yarn run v1.22.19                                                                                        
$ yarn prepack && depcheck && createdb graphile_worker_test || true && psql -X -v GRAPHILE_WORKER_SCHEMA="${GRAPHILE_WORKER_SCHEMA:-graphile_worker}" -v ON_ERROR_STOP=1 -f __tests__/reset-db.sql graphile_worker_
test && jest -i                                     
$ rm -Rf dist && tsc && chmod +x dist/cli.js
Unused dependencies                                                                                                                                                                                                
* @types/debug                                      
Unused devDependencies                              
* @types/jest                                                                                            
* @typescript-eslint/eslint-plugin                                                                       
* @typescript-eslint/parser                                                                              
* eslint-config-prettier                                                                                 
* eslint-plugin-import                              
* eslint-plugin-jest                                
* eslint-plugin-simple-import-sort                                                                                                                                                                                 
* eslint_d                                          
* ts-node                                           
psql: error: connection to server on socket "/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
error Command failed with exit code 2.
```

However, `docker compose exec app yarn jest -i` passes, except for the test `providing just PGHOST and PGDATABASE is possible`, which fails on a clean checkout.

2023-01-16 16:12 UTC, octavifs commented
+1 to the feature. We'd relly benefit at work from being able to specify a job_key on cron jobs. I would be happy to help, if possible.

2023-01-23 11:17 UTC, benjie requested changes
This needs to be reworked on top of the latest Worker because I changed a number of internals, but I'm generally in favour of it - great work!

And sorry it's taken so long to get around to, I've been more than a little overwhelmed with work recently 😅

2023-01-23 11:17 UTC, benjie commented on __tests__/cron-timing.test.ts
> +    let jobs = await getJobs(pgPool);
Let's check the jobs match

```suggestion
    const jobs = await getJobs(pgPool);
```

2023-01-23 11:17 UTC, benjie commented on __tests__/cron-timing.test.ts
> +    ]);
Not sure if this is quite the right assertion, but something like this:

```suggestion
    const jobs2 = await getJobs(pgPool);
    expect(jobs2).toEqual([
      expect.objectContaining({ task_identifier: "my_task", key: "foo", id: jobs[0].id }),
    ]);
```

2023-01-23 11:17 UTC, benjie commented on src/cronConstants.ts
> +export const CRONTAB_OPTIONS_JOB_KEY_MODE = /^(replace|preserve_run_at)$/;
Should we also allow `unsafe_dedupe`?

2023-02-15 13:19 UTC, you-fail-me commented
Very much looking forward for this to get merged, would really help me a lot in prod

2023-05-08 21:36 UTC, a613 commented
This is a pretty critical omission as cronjobs are, by their fixed interval nature, prone to running into each other if the work takes too long. Can we possibly get some attention on this?

2023-10-19 08:41 UTC, benjie approved these changes
Thanks for the great work @spiffytech :raised_hands: 

I've merged the latest, applied my suggestions, added a couple additional assertions to the test, and tidied up parsing of the opts string to avoid being too noisy. This is good to go now!

2023-10-19 08:47 UTC, benjie approved these changes

2023-10-19 08:49 UTC, merged